branch-defaults:
  default:
    environment: development
    group_suffix: null
global:
  application_name: paul044-cart-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: personalAccount
  repository: null
  sc: null
  workspace_type: Application
